### ISSUE TITLE
Review permissions implementation and endpoints

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl-server#18]
- [x] Review the `finDelegateTo` property so that it always points to the element whose permissions are the effective permissions of an element, **including when `delegate = false`**, in which case `finDelegateTo` should be the same `elementId`. Once this is done, remove all logic of the type `if (delegate) { ... } ` that is not needed (for example [here](https://github.com/uprtcl/js-uprtcl-server/blob/develop/src/services/access/access.service.ts#L115), [here](https://github.com/uprtcl/js-uprtcl-server/blob/develop/src/services/access/access.service.ts#L182), and [here](https://github.com/uprtcl/js-uprtcl-server/blob/develop/src/services/access/access.service.ts#L51) ). Make sure current tests pass.

- [x] Add new tests to `uprtcl.test.ts` that changes the `delegate` property of an element. Consider all possible cases:
    - [ ] `delegate` of perspective A passes from `false` to `true` and new `delegateTo` is perspective C who has `delegate = false`. Perspectve B has `delegate = true` and `delegateTo = perspective A`.
    - [ ] `delegate` of perspective A passes from `false` to `true` and new `delegateTo` is perspective C who has `delegate = true` and `delegateTo = perspective D`. Perspectve B has `delegate = true` and `delegateTo = perspective A`.
    - [ ] `delegate` of perspective A passes from `true` to `false` and delegateTo was `perspective C`. Perspectve B has `delegate = true` and `delegateTo = perspective A`.

- [x] Review the endpoints related to permissions and remove the generic ones 
- `path: "/uprtcl/1/accessConfig/:elementId"`
- `path: "/uprtcl/1/permissions/:elementId"`

    Replace them with task-specific endpoints as follows:

    `path: "/uprtcl/1/accessConfig/:elementId/delegate?delegate=value&delegateTo=value"`

    Which will receive two query parameters `delegate` and `delegateTo`. The endpoint will set  `delegate` property of the accessConfig of `elementId` to `true` or `false`. If `true`, the `delegateTo` query parameter is checked and used to set or update the `delegateTo` property.

**Comment by pepoospina** [comment]
- [ ] check why cascade is needed and cant filter by delegateTo ` Got error: Attribute delegateTo is not valid scalar type while running:` (forum credentials).
- [ ] why adding ~delegateTo to the "C" level, hides C2 and shows C1 and D1? it seems its because C2 don't have children (no one `delegateTo` to it). Maybe related to @cascade?
- [ ] How can we use this query as an alias to set all the `finDelegatedTo` of the elements found by the query? even if not recursive. Using [upsert](https://dgraph.io/docs/master/mutations/conditional-upsert/)
- [ ] Can we do the @recursive query? (so that all children `finDelegateTo` are set with one upsert mutation)
- [ ] If we cant, which is probably the case, because of multiple level query. Is it possible to change the data schema so that @recurse can be used? for example, remove the `accessConfig` node, set `accessConfig` as `Perspective` properties directly and use `delegateTo` pointing to a `uid`

**Comment by sotous** [comment]
So, this is the query that I worked around regarding the first point:

`delegatingFromAccessConfigs as var(func: eq(xid, "${elementId}")) {
            accessConfig : ~delegateTo {
              uid
            }
          }`

**Comment by pepoospina** [comment]
It makes sense. I think its time to get rid of the AccessControl type, and just put all its properties (`delegate`, `delegateTo`, `finDelegatedTo` and `permissions` to the Perspective object itself)
