### ISSUE TITLE
Update backend proposals

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl-server#32]
Update the backend proposals to store the newPerspectives array in the Proposal object.

The proposals strategy changed, and now the perspectives are not created by the person who make the proposal, but are created by the person who accepts the proposals, at the moment they accept it.

Having the option for people to create perspectives as if they were someone else was an issue on other providers and also on web2, where the this.updatePerspective inside the createAndInitePerspective method would if called at proposal creation (that was the case before).

There is no need to store the perspective or the heads as nodes in the DB, just the string with their xid is enough. Now, proposal execution is performed by the frontend by calling the createPerspetive and updateHeads associated to a proposal object.

**Comment by pepoospina** [comment]
I have done the first modifications already in [this branch](https://github.com/uprtcl/js-uprtcl-server/tree/context-refactor/src), but I'm getting a weird error message when trying to execute the DB request [here](https://github.com/uprtcl/js-uprtcl-server/blob/context-refactor/src/services/proposals/proposals.repository.ts#L157). 

It throws with

```
TypeError: Cannot read property "'message'" of undefined
```

Can you please give me a hand @sotous  and check what could be causing this?

**Comment by sotous** [comment]
Sure thing!

**Comment by sotous** [comment]
So the issue was given by a typo and an unnecessary query set before the mutation. 

![image](https://user-images.githubusercontent.com/16869766/94976115-7b6baa80-04d9-11eb-862f-9cd24e4d8825.png)

![image](https://user-images.githubusercontent.com/16869766/94976134-8c1c2080-04d9-11eb-80b7-91ec5cc5c556.png)

Also, I adapted tests to pass through the new behavior of the proposals.

**Comment by pepoospina** [comment]
I put that typo on purpose to see if it would fail with a different error and tried without emoty query. Did you manage to run a test for createProposal with `updates` and `newPerspectives`?

If so, then it could have been something local on my machine, maybe I should have prune the DB.

**Comment by sotous** [comment]
Yes indeed, also I removed the `setQuery` function, since you are only performing a mutation, a query is not needed. All tests passed. It would be nice to check as well in your local DB.
