### ISSUE TITLE
Add links next to children

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl-server#38]
Assume head updates include, beside the list of added/removed Chidren, the list of added/removed Links. Store them as edges inside the updatePerspectiveQuery function, just next to where the perspective head is set.

These edges are provided by the frontend, and will be used by the first explore/search feature.

To add the edges these need to be added to the DB schema, inside the Perspective type, and they should be marged as @reverse indexed to be able to query `~linksTo`.

Use the `children` edges as an example [in the schema](https://github.com/uprtcl/js-uprtcl-server/blob/develop/src/services/uprtcl/uprtcl.schema.ts#L29) and for [indexing](https://github.com/uprtcl/js-uprtcl-server/blob/develop/src/services/uprtcl/uprtcl.schema.ts#L73).

**Comment by milieuChris** [comment]
From Pepo:

_1) You create the "concept node" as a placeholder.

2) You create three blog posts as posts with a link to the concept node.

3) You explore for all nodes with links to the concept node and get the three posts

First you need to add the concept of <link> edges_

**Comment by pepoospina** [comment]
The comment above is for changes on the frontend. That is now another issue. That depends on this one
