### ISSUE TITLE
Add search "above" a perspective.

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl-server#54]
Equivalent to under, but filter the reverse ecosystem of a perspective.

**Comment by sotous** [comment]
Latest updates about the feature here:

https://github.com/uprtcl/js-uprtcl-dev/tree/above-search-option

**Comment by pepoospina** [comment]
I was reviewing the implementation and it seems the `levels` property of the `SearchOptionsEcoJoin` object are being applied to all elements in the under/above set, and not to each element. And that the `levels` property of each `JoinElement` is not used.

Should we remove the levels in the `SearchOptionsEcoJoin` and use only the levels of each element in the `JoinElement[]` array?

**Comment by pepoospina** [comment]
Ok, I've seen now that those levels was there to be applied to the forks property. Maybe they can be added inside the `forks` option to be more explicit.
