### ISSUE TITLE
Add "forks" flag to search

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/js-uprtcl-server#55]
Add a forks flag that will extend the `filtered` intermediate result to also (independent) forks of the matched perspective.

I'm not sure if this is entirely possible in general, but it does fit very well if we reconsider the `getOtherIndpPerspectives` as a explore case with `under = perspectiveId`, and a `forks` in `SearchOptions` being `true`.

This is why maybe it is just a special case of search function.

**Comment by pepoospina** [comment]
I tried to make a patch and connect the getIndependentPerspectives function into the current fetchPerspectives one as a "special" case when forks option is provided, (setting level = 0).

here is what I did (all three repos)
https://github.com/uprtcl/js-uprtcl-dev/tree/get-block-forks

But the forks are not being detected. We should check this together @sotous

**Comment by sotous** [comment]
@pepoospina I modified the schema in order to be able to "reverse" the context.

This enable us to have a more friendly query at the time of looking for independent perspectives, this is how the new `DQL` will look: 

```
    // get the objective context for a given perspective.
      perspectiveContext(func: eq(xid, ${perspectiveId})) { 
        context {
          targetCon as uid
        }
      }

    // Verify independent perspectives criteria for children perspectives
    contextRef(func: uid(targetCon)) {
       perspectivesOfContext: ~context {
          childPerspective as uid
          xid
          ~children {
            context @filter(not(uid(targetCon)))
          }
        }
    }

    // Verify independent perspectives criteria with orphan perspectives as reference.
    orphanContextRef(func: uid(targetCon)) {
      perspectivesOfContext: ~context @filter(not(uid(childPerspective))) {
        xid
      }
    }
```

**Comment by sotous** [comment]
Permissions checks have been added. This can be tested and seen here:

https://github.com/uprtcl/js-uprtcl-dev/tree/get-block-forks-sotous

**Comment by sotous** [comment]
Latest updates about the feature can be seen here:

https://github.com/uprtcl/js-uprtcl-dev/tree/get-block-forks-sotous
